
[functions.analytics-ingest]
enabled = true
verify_jwt = true
import_map = "./functions/analytics-ingest/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/analytics-ingest/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/analytics-ingest/*.html" ]

[functions.create-cashfree-order]
enabled = true
verify_jwt = true
import_map = "./functions/create-cashfree-order/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-cashfree-order/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-cashfree-order/*.html" ]

[functions.cashfree-webhook-handler]
enabled = true
verify_jwt = true
import_map = "./functions/cashfree-webhook-handler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/cashfree-webhook-handler/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/cashfree-webhook-handler/*.html" ]
